### ISSUE TITLE
Customize GraphiQL to send Header variables

### ISSUE THREAD

**Issue by elenigen** [graphql-java/graphql-spring-boot#101]
By implementing a solution with an API Key (JWT), it is no longer possible to use GraphiQL 😢 

It would be nice to customize the HTML part of GraphiQL so it's possible to include the API Key in the queries, the maintainers of the original projet are not open to this idea, but I still think it's a real need, especially for projects like graphql-spring-boot where everything is already packaged for us.

https://github.com/graphql/graphiql/issues/59#issuecomment-179137697

**Comment by oliemansm** [comment]
Aren't you familiar with [Insomnia](https://insomnia.rest/)? It's like Postman+. Proper GraphQL support including ability to set headers like your API Key! You can save all your queries in folders as well. I use GraphiQL hardly anymore since I can test all my use cases with Insomnia.

**Comment by elenigen** [comment]
I was not aware of this tool, thanks for sharing, for sure I will start using it ... but I still think it would be even better to have GraphiQL working with an API Key.

**Comment by oliemansm** [comment]
@elenigen I took a look at the GraphiQL starter keeping this issue in mind. What we could do is add a property `graphiql.headers.authorization` that you could use to set your token, e.g. `Bearer <jwt>`. If you generate tokens with a long enough expiration time you could use that for testing. 

Would that work for you?
