### ISSUE TITLE
Trying to run example-spring-common, getting error

### ISSUE THREAD

**Issue by aljacinto** [graphql-java/graphql-spring-boot#103]
Hi, I started the **example-spring-common** app then went to graphiql but getting websocket error, it looks like the endpoint /graphql doesn't exists.  I compared it to the log of app **example** and it's not registering this endpoint:

`2018-07-28 22:38:57.183  INFO 90462 --- [           main] o.s.w.s.s.s.ServerEndpointExporter       : Registering ServerEndpointConfig: ServerEndpointRegistration for path '/subscriptions': class graphql.servlet.GraphQLWebsocketServlet
`
I was trying to find docs for the example as well, is there one?  I can probably do a PR, let me know if one doesn't exist.

Thanks in advance.

**Comment by oliemansm** [comment]
Hi Alex,

I think use of spring-common is deprecated seeing the remark about the latest supported version. Can you confirm @apottere? Take a look at this part of the readme including the links: [GraphQL Spring Commons](https://github.com/graphql-java/graphql-spring-boot#graphql-spring-common-latest-supported-version-311).

There is good support for [graphql-java-tools](https://github.com/graphql-java/graphql-java-tools) though, [example-graphql-subscription](https://github.com/graphql-java/graphql-spring-boot/tree/master/example-graphql-subscription) on how to set that up for subscriptions. I added that example based on [graphql-java-subscription-example](https://github.com/graphql-java/graphql-java-subscription-example) at first to verify the subscriptions implementation. Didn't get around to adding proper readme for it yet.

**Comment by aljacinto** [comment]
Thanks @oliemansm I tried all the examples and tell me if these are correct:

- **example** springboot with schema generated from bean
- **example-graphql-subscription* how to do subscription
- **example-graphql-tools* schema comes from .graphqls file then it uses resolvers for the query
- **example-spring-common* does not work but it looks like this one is using annotations to generate schema

**Comment by oliemansm** [comment]
That's correct!

**Comment by oliemansm** [comment]
@aljacinto Were you able to get going with this info?

**Comment by aljacinto** [comment]
yes, thanks @oliemansm.
