### ISSUE TITLE
GraphQL is not getting exposed on a different endpoint 

### ISSUE THREAD

**Issue by sharmmoh1983** [graphql-java/graphql-spring-boot#107]
I have tried using

graphql:
servlet:
mapping: /test
enabled: true
corsEnabled: true

GraphQL is not getting exposed on a different endpoint
I did not see any which way where /graphql van be exposed to some other point
Also /graphql is giving 400 bad request, it is only expecting query parameters

Only /graphiql is working which is a html page

How can we expose /graphql or any user defined url as as endpoint with post body?

**Comment by oliemansm** [comment]
Just tested again and it does work for me now. Think I forgot to save it or something in the previous test. You only need this part btw:
```yaml
graphql:
  servlet:
    mapping: /test
```
Seems to be something with your local config.

**Comment by sharmmoh1983** [comment]
It worked for me when giving configurtion

`graphql.servlet.mapping=/test`

But there is one more issue , I can't use /graphql or /test with POST body, it gives 400 error code
it is only taking query parameters

**Comment by oliemansm** [comment]
Sounds like you added yaml style configuration in your properties file before then.

GraphiQL uses POST as well, so it does accept it. Could be a problem with your model or schema. In that case there should be a stack trace. Why don't you start with the working example `example-graphql-tools` and work from there. Current version is stable and functioning.

**Comment by sharmmoh1983** [comment]
@oliemansm 
I am talking  about /graphql and not /graphiql . For real use case I will be exposing /graphql and not 
/graphiql which is just a UI and can't be shared with consumers in the form of API.
Also example-graphql-tools also follow the same lines

**Comment by oliemansm** [comment]
GraphiQL sends POST requests to /graphql. Confirming that it accepts POST requests.

**Comment by sharmmoh1983** [comment]
@oliemansm 
I beg to differ  /graphqln accepts query parameter



Please find the following snapshot
![image](https://user-images.githubusercontent.com/8494468/43581909-e67b1510-969d-11e8-83df-2f1d72a4a17e.png)

![image](https://user-images.githubusercontent.com/8494468/43581942-06fbdc2a-969e-11e8-858e-da36b77bf11b.png)

**Comment by oliemansm** [comment]
Well yes, it also accepts GET parameters. That's not the problem you reported though. You reported that it doesn't accept POST requests.

**Comment by sharmmoh1983** [comment]
@oliemansm 
Yes you can see from the above snapshot same POST request not working..
Also I captured the source code of graphql UI

![image](https://user-images.githubusercontent.com/8494468/43582847-1087ba7c-96a1-11e8-9ea5-f7301d02be5a.png)

If you see the snapshot ,there is proper JSON message sent which we never mentioned in GraphQL UI

**Comment by oliemansm** [comment]
Set `graphiql.endpoint=/test` as well. Don't know why, but for some reason it currently needs to be set separately.

**Comment by oliemansm** [comment]
Look at all the settings of a successful GraphiQL post and copy that behavior. Investigate online for example at https://graphql.org/learn/. You're basically asking general GraphQL questions now for which there a lot of resources readily available online.

**Comment by sharmmoh1983** [comment]
@oliemansm 
Thanks for your support

I have got my answer

Following POST body works fine 
```
POST
{"query": "{ findAllBooks { id } } "}

So there is some tweaking happening from grqphqlUI to graphql endpoint
```

**Comment by lazarevd** [comment]
`graphql.url = test `
in **application.properties** 
helped

**Comment by menilub** [comment]
same problem - need to fix the documentation 
setting url by: 
`graphql.servlet.mapping= `
not working
`graphql.url = `
works

**Comment by ooga** [comment]
I reproduce the same issue.
It depends on the spring type

webmvc use `graphql.servlet.mapping`
webflux use `graphql.url`

Could be nice to have the same property for both

**Comment by oliemansm** [comment]
@ooga you're correct. I think there's an open discussion or issue where I mentioned this too.
