### ISSUE TITLE
add generic get to GraphQLResponse

### ISSUE THREAD

**Issue by bassmake** [graphql-java/graphql-spring-boot#121]
currently only get with String is supported:
```
    public String get(String path) {
        return context.read(path);
    }
```
could be there also generic
```
    public <T> T get(String path, Class<T> type) {
        return context.read(path, type);
    }
```
?

**Comment by oliemansm** [comment]
Added it for the next release. You can grab the context from it directly in the meantime using `context()`. Was thinking of perhaps adding some primitive convenience getters as well, such as `getInt(String path)`, `getBoolean(String path)`, etc.
