### ISSUE TITLE
Subscription: Exception while fetching data

### ISSUE THREAD

**Issue by rvanrees** [graphql-java/graphql-spring-boot#126]
Hello,

When I want to run the subscription [**stockQuotes**](https://github.com/graphql-java/graphql-spring-boot/tree/master/example-graphql-subscription) I get the following error:

`"message": "Exception while fetching data (/stockQuotes/stockCode) : Expected source object to be an instance of 'subscription.resolvers.StockPriceUpdate' but instead got 'io.reactivex.internal.operators.flowable.FlowableFilter'"`

Can someone explain what I'm doing wrong?

Thanks!

**Comment by oliemansm** [comment]
This is when you just run the example as is?

**Comment by rvanrees** [comment]
Yes, I just copied the code.

**Comment by oliemansm** [comment]
Ok, that's not good. Will take a look at it later, thanks for reporting.

**Comment by oliemansm** [comment]
Making the method `Publisher<StockPriceUpdate> stockQuotes(List<String> stockCodes)` public should fix it for now. Issue will be fixed in next release of **graphql-java-tools**. Caused by bug https://github.com/graphql-java/graphql-java-tools/issues/182.
