### ISSUE TITLE
Dependency Error in graphiql-spring-boot-starter

### ISSUE THREAD

**Issue by mSenussi** [graphql-java/graphql-spring-boot#14]
`Failed to collect dependencies at com.graphql-java:graphiql-spring-boot-starter:jar:3.3.0 -> com.graphql-java:graphiql-spring-boot-autoconfigure:jar:3.3.0 -> org.webjars.npm:react:jar:15.5.4 -> org.webjars.npm:fbjs:jar:0.9.0-alpha.2 -> org.webjars.npm:fbjs-css-vars:jar:[1.0.0,2): No versions available for org.webjars.npm:fbjs-css-vars:jar:[1.0.0,2) within specified range `

**Comment by ptcuops** [comment]
The artifact in question, org.webjars.npm:fbjs-css-vars:jar, does not appear to be available from the main maven repository.

**Comment by ptcuops** [comment]
This appears to be a problem upstream with org.webjars.npm:fbjs.

**Comment by dimazelinskyi** [comment]
The same for me.

**Comment by oliemansm** [comment]
Same for me. Got it working for now by using the following maven config.
```xml
    <dependency>
      <groupId>com.graphql-java</groupId>
      <artifactId>graphiql-spring-boot-starter</artifactId>
      <version>${graphql.version}</version>
      <exclusions>
        <exclusion>
          <groupId>com.graphql-java</groupId>
          <artifactId>graphiql-spring-boot-autoconfigure</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.graphql-java</groupId>
      <artifactId>graphiql-spring-boot-autoconfigure</artifactId>
      <version>${graphql.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.webjars.npm</groupId>
          <artifactId>react</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.webjars.npm</groupId>
          <artifactId>react-dom</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.webjars.npm</groupId>
      <artifactId>react</artifactId>
      <version>15.5.4</version>
      <exclusions>
        <exclusion>
          <groupId>org.webjars.npm</groupId>
          <artifactId>fbjs</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.webjars.npm</groupId>
      <artifactId>react-dom</artifactId>
      <version>15.5.4</version>
      <exclusions>
        <exclusion>
          <groupId>org.webjars.npm</groupId>
          <artifactId>fbjs</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.webjars.npm</groupId>
      <artifactId>fbjs</artifactId>
      <version>0.8.12</version>
    </dependency>
```

**Comment by oliemansm** [comment]
Now another dependency is broken. Caused by the `codemirror` package depending on two `org.webjars.npm` packages. Because of the instability of those webjar packages I'm not using this graphiql starter anymore, but simply included my own graphiql html page as resource, which retrieves its dependencies from a cdn for now. Would advise the same approach for this starter, or include the dependencies directly as static resources (there aren't that many anyway). If I find some time, I'll create a PR to address this.
