### ISSUE TITLE
spring-graphql-common is out of sync with graphql-java

### ISSUE THREAD

**Issue by orclev** [graphql-java/graphql-spring-boot#16]
The latest version of graphql-java (3.0.0) changed DataFetchingEnvironment to an interface instead of a class, but spring-graphql-common inside of ReflectionGraphQLDataFetcher is expecting DataFetchingEnvironment to be a class leading to a runtime exception being thrown. 

Technically this issue is with spring-graphql-common, but it looks like that project hasn't had an update in over a year. There do appear to be several forks, including one that has updated the dependency to use graphql-java 3.0.0, but that fork doesn't seem to exist on any nexus repo requiring that you check out and build that fork in order to work around it.

Until spring-graphql-common is updated the version of graphql-java should be constrained to an earlier version, or else support for spring-graphql-common needs to be temporarily disabled.

**Comment by apottere** [comment]
I thought I had already disabled it, but I must have forgotten.  I'll disable it now.  If anyone is using spring-graphql-common and wants to start maintaining it, we can fork it into graphql-java, but I don't believe that project should hold the spring-boot starter on an old version of graphql-java

**Comment by apottere** [comment]
I added a comment to the readme with spring-graphql-common's latest supported version.
