### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by scso** [graphql-java/graphql-spring-boot#18]
Upon firing
./gradlew --refresh-dependencies --info clean build

Getting following error!
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':graphql-sample-app:compileClasspath'.
> Could not find any matches for org.webjars.npm:graphql-language-service-interface:[0.0.16,0.0.17) as no versions of org.webjars.npm:graphql-language-service-interface are available.
  Required by:
      project :graphql-sample-app > project :graphiql-spring-boot-starter > project :graphiql-spring-boot-autoconfigure > org.webjars.npm:graphiql:0.10.1 > org.webjars.npm:codemirror-graphql:0.6.9
> Could not find any matches for org.webjars.npm:graphql-language-service-parser:[0.0.14,0.0.15) as no versions of org.webjars.npm:graphql-language-service-parser are available.
  Required by:
      project :graphql-sample-app > project :graphiql-spring-boot-starter > project :graphiql-spring-boot-autoconfigure > org.webjars.npm:graphiql:0.10.1 > org.webjars.npm:codemirror-graphql:0.6.9

**Comment by thecaddy** [comment]
Having the same issue with build.  Is this project still being maintained?

**Comment by apottere** [comment]
Yes, I'm going to have time to update it tomorrow.

**Comment by thecaddy** [comment]
@apottere thanks for the quick response.

Any idea why these dependencies were removed?  I was under the impression maven packages can't be deleted.
We added the below exclusion and it will build.


```
                <exclusion>
                    <groupId>org.webjars.npm</groupId>
                    <artifactId>codemirror-graphql</artifactId>
                </exclusion>
```

**Comment by apottere** [comment]
I'm honestly not sure how webjars work, as it was added in a PR.  I'm just as surprised at how they seem to disappear occasionally...
