### ISSUE TITLE
Injecting Spring beans into data fetchers

### ISSUE THREAD

**Issue by mushketyk** [graphql-java/graphql-spring-boot#20]
I am puzzled about how should I inject spring beans into data fetchers.
One way could be to pass `ApplicationContext` into `graphQL.execute` like this:

```java
@Autowired
ApplicationContext applicationContext
...
graphQL.execute("{query}", applicationContext).<Map<String, Object>> getData()
```

Then DataFetcher implementation would look like:

```java
class MovieDataFetcher implements DataFetcher<List<Item>> {

    @Override
    List<Item> get(DataFetchingEnvironment environment) {
        ApplicationContext applicationContext = environment.<ApplicationContext> getContext()
        MoviesRepository moviesRepository = applicationContext.getBean(MoviesRepository)
        return moviesRepository.findAll()
    }
}
```

What is the preferred way to do this with `graphql-spring-boot`?

**Comment by apottere** [comment]
That seems like a good solution.  Right now, the servlet used doesn't expose a way to alter the context:
```
    @Override
    protected GraphQLContext createContext(Optional<HttpServletRequest> request, Optional<HttpServletResponse> response) {
        return new GraphQLContext(request, response);
    }
```

That could be extended to allow you to pass your own context creator that adds the applicationContext.

Static datafetchers are annoying, which is why I created my own library (https://github.com/graphql-java/graphql-java-tools) that let you have state, which means you can `@Autowire` beans into them.

**Comment by mushketyk** [comment]
Hi @apottere 
Thank you for the response.

I think it would be a good idea to allow altering the context to increase application flexibility.
Regarding `graphql-java-tools`. Does it work with `graphql-annotations`?

**Comment by apottere** [comment]
No, it's not compatible with annotations.  They're both graphql-schema generation libraries, but they have different philosophies :)

**Comment by apottere** [comment]
Currently releasing this: https://github.com/graphql-java/graphql-java-servlet/commit/0b62669f4b157f0d84919458a5b787c410a09adc

Once that's done, I'll update this project to expose it.

**Comment by mushketyk** [comment]
Thank you for the update @apottere. I think this commit may help to close #5 as well!

**Comment by mushketyk** [comment]
A temporary workaround is to use `graphql-java-servlet` instead of `graphql-spring-boot` and define these beans:

```java
    // Register GraphQL servlet
    @Bean
    ServletRegistrationBean servletRegistrationBean() {
        return new ServletRegistrationBean(graphQLServlet(), "/graphql/*");
    }

    @Bean
    GraphQLServlet graphQLServlet() {
        // Return custom GraphQL context
        new SimpleGraphQLServlet(graphQLSchema()) {
            @Override
            protected GraphQLContext createContext(Optional<HttpServletRequest> request, Optional<HttpServletResponse> response) {
                return new SpringGraphQLContext(request, response, applicationContext);
            }
        }
    }
```

and SpringGraphQLContext would look like this:

```java
class SpringGraphQLContext extends GraphQLContext {

    private ApplicationContext applicationContext

    SpringGraphQLContext(Optional<HttpServletRequest> request,
                         Optional<HttpServletResponse> response,
                         ApplicationContext applicationContext) {
        super(request, response);
        this.applicationContext = applicationContext;
    }

    ApplicationContext getApplicationContext() {
        return applicationContext;
    }
}
```

than one can access ApplicationContext in a data fetcher:

```java
    List<Movie> get(DataFetchingEnvironment environment) {
        ApplicationContext applicationContext = environment.<SpringGraphQLContext> getContext().getApplicationContext()
    }
```

**Comment by apottere** [comment]
graphql-spring-boot `3.6.0` is released, and allows you to specify a `GraphQLContextBuilder` bean.
