### ISSUE TITLE
How to assign graphiql to a different path

### ISSUE THREAD

**Issue by mushketyk** [graphql-java/graphql-spring-boot#21]
README suggests that `graphiql` is available at the root `/`. Is there any way to assign it to a different path?

**Comment by apottere** [comment]
The graphiql index.html is exposed by placing it in `src/main/resources/META-INF/resources/`.  I don't know enough about how spring-boot handles static resources to know if that can be changed by a property or not.

**Comment by apottere** [comment]
https://github.com/graphql-java/graphql-spring-boot#enable-graphql-servlet
