### ISSUE TITLE
Disable graphiql in production

### ISSUE THREAD

**Issue by mushketyk** [graphql-java/graphql-spring-boot#22]
Is there a way to have `graphiql-spring-boot-starter` dependency in the project, but disable it in a particular Spring profile?

**Comment by apottere** [comment]
Per the comment on https://github.com/graphql-java/graphql-spring-boot/issues/21#issuecomment-317086287, this isn't possible right now because there isn't actually an autoconfiguration class being run.  The solution to both issues is probably to add an autoconfiguration class.

**Comment by mushketyk** [comment]
Hi @apottere 

I think it would be nice to have this autoconfiguration class if this is possible.

**Comment by apottere** [comment]
I added instructions in the readme on graphiql properties in `3.6.0` https://github.com/graphql-java/graphql-spring-boot#enable-graphql-servlet
