### ISSUE TITLE
GraphiQL broken in 3.6.0

### ISSUE THREAD

**Issue by martin-walsh** [graphql-java/graphql-spring-boot#26]
See https://github.com/graphql-java/graphql-spring-boot/commit/4cb422c663d579a25b14b326c37c1fe94ba1f981

GraphiQL page is rendered as text.
![image](https://user-images.githubusercontent.com/3782048/29652032-f3770a64-88e6-11e7-8731-5b8de4b6cdb8.png)

**Comment by martin-walsh** [comment]
See https://github.com/graphql-java/graphql-spring-boot/pull/27

**Comment by oliemansm** [comment]
My open pull request adresses this issue.

**Comment by apottere** [comment]
This is fixed in `3.7.0`, syncing now.
