### ISSUE TITLE
Sample app doesn't autoconfigure servlet

### ISSUE THREAD

**Issue by jansauer** [graphql-java/graphql-spring-boot#28]
Spun off from #15. The sample app of the current master does start but without a working graphql.

### Steps to reproduce:
```
$ git clone https://github.com/graphql-java/graphql-spring-boot.git
$ cd graphql-spring-boot/graphql-sample-app
$ gradle bootRun
```
Open graphiql (http://localhost:9000/graphiql). `graphiql` loads but does not find a `graphql` endpoint.
```
{
  "timestamp": 1503588828841,
  "status": 404,
  "error": "Not Found",
  "message": "No message available",
  "path": "/graphql"
}
```

### Hints:
It took me some time to learn that `graphql` does not start as a normal endpoint. You will find logs like ...
```
2017-08-24 17:32:05.223  INFO 21175 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/graphiql]}" onto public void com.oembedler.moon.graphiql.boot.GraphiQLController.graphiql(javax
```
but not for graphql. graphql should be listed like a filter ...
```
2017-08-24 17:32:04.848  INFO 21175 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'metricsFilter' to: [/*]
```
If you start the app with `MANAGEMENT_SECURITY_ENABLED=false gradle bootRun` you can open `http://localhost:9000/autoconfig`. `GraphQLJavaToolsAutoConfiguration` is listed there as `negativeMatches`
```
GraphQLJavaToolsAutoConfiguration: {
  notMatched: [
    {
      condition: "OnClassCondition",
      message: "@ConditionalOnClass did not find required class 'com.coxautodev.graphql.tools.SchemaParser'"
    }
  ],
  matched: [ ]
},
GraphQLWebAutoConfiguration: {
  notMatched: [
    {
      condition: "OnBeanCondition",
      message: "@ConditionalOnBean (types: 
      graphql.schema.GraphQLSchema,graphql.servlet.GraphQLSchemaProvider; SearchStrategy: all) did not find any beans"
    }
  ],
  matched: [
    {
      condition: "OnClassCondition",
      message: "@ConditionalOnClass found required class 'org.springframework.web.servlet.DispatcherServlet'; @ConditionalOnMissingClass did not find unwanted class"
    },
    {
      condition: "OnWebApplicationCondition",
      message: "@ConditionalOnWebApplication (required) found StandardServletEnvironment"
    },
    {
      condition: "OnPropertyCondition",
      message: "@ConditionalOnProperty (graphql.servlet.enabled=true) matched"
    }
  ]
},
```

**Comment by apottere** [comment]
Oh, I didn't realize the sample app itself wasn't working.  I'll take a look.

**Comment by jansauer** [comment]
thx. I had some problems starting with graphql and java. I was able to create my own sample app but  was unable to find the problem in this sample.

**Comment by coyotesqrl** [comment]
The timing here is fortuitous. I'm trying to figure out how to get this to work this afternoon and coming up against this. From my little investigation so far, it looks like `graphql-spring-boot-autoconfigure` isn't actually auto-configuring itself the same way its graphiql counterpart is.

**Comment by apottere** [comment]
For everyone here, I made a really simple example application.  The existing example application was specifically for spring-graphql-common, a project that's no longer maintained.  The new example doesn't use an external library to create the schema, it just uses the graphql-java builders.

The new example is here: https://github.com/graphql-java/graphql-spring-boot/tree/master/example

Let me know if you have any other issues, the new example worked just fine for me.
