### ISSUE TITLE
Configure GraphQLServlet object mapper

### ISSUE THREAD

**Issue by miguelaferreira** [graphql-java/graphql-spring-boot#32]
It's possible to configure the object mapper used by the `GraphQLServlet` via a custom implementation of the (functional) interface `ObjectMapperConfigurer` (see graphql-java/graphql-java-servlet@8f557852856ca5ed2eea59fce7a56fc61224b71d).

I would expect it to be possible to register a bean of such implementation in the application context and have it injected in the `GraphQLServlet`. However this doesn't seem to be possible yet.

Here's what I'm trying to do:
```java
@SpringBootApplication
public class Application {

(...)

    @Bean
    ObjectMapperConfigurer objectMapperConfigurer() {
        return mapper -> mapper.registerModule(new JavaTimeModule());
    }

(...)

}
```

Is this something that needs to be implemented yet? Or am I going about it the wrong way?

**Comment by apottere** [comment]
Are you using 3.9.0? I released this change yesterday which should support that: https://github.com/graphql-java/graphql-spring-boot/commit/fff13ab947ea49ecfa3afc5235a906fb24e77163

**Comment by miguelaferreira** [comment]
Yes, I am. I've just debugged the bootstrapping of the application and I do see that my own configuration is being applied to the object mapper. So, answering my own question, configuration works just fine. I'll close the issue now and if relevant I'll post here for reference how I solved my problem.

**Comment by miguelaferreira** [comment]
A bit more debugging shows that the object mapper used to deserialise inputs from mutations is not the same as the one I configured via a bean in the `Application` class (object reference changes).

When I debug the bootstrapping of the application I see that the module `JavaTimeModule` is added to a object mapper that already contains the `Jdk8Module` (as expected).

Before my configuration is applied:
![before-configuration](https://user-images.githubusercontent.com/4670993/30381090-b16a64e4-989b-11e7-9009-8fd59167d5f3.png)

After my configuration is applied:
![after-configuration](https://user-images.githubusercontent.com/4670993/30381112-c5772b2a-989b-11e7-8110-4801c761abb3.png)

However, when handling the input of a mutation the object mapper no longer has the `JavaTimeModule`.

![handling-mutation](https://user-images.githubusercontent.com/4670993/30381126-cab120d2-989b-11e7-8a3e-ed883be4d93a.png)

**Comment by miguelaferreira** [comment]
It seems that the object mapper that deserialises the values passed into the mutation is not the one in the servlet but instead it's the one in ` com.coxautodev.graphql.tools.MethodFieldResolver`.

**Comment by miguelaferreira** [comment]
I've fixed my problem (deserialising LocalDateTime objects passed in as inputs to mutations) by also registering a bean to configure the object mapper used by `java-graphql-tools` (which I use to parse the schema definition).

So the final configuration looks like this:
```java
@SpringBootApplication
public class Application {

(...)

    @Bean
    ObjectMapperConfigurer objectMapperConfigurer() {
        return mapper -> mapper.registerModule(new JavaTimeModule());
    }

    @Bean
    SchemaParserOptions schemaParserOptions() {
        return SchemaParserOptions.newOptions()
                                  .objectMapperConfigurer((ObjectMapper mapper, ObjectMapperConfigurerContext context) -> mapper.registerModule(new JavaTimeModule()))
                                  .build();
    }
(...)

}
```

**Comment by apottere** [comment]
Ah, yeah.  The servlet object mapper handles parsing variables and output, but the graphql-java-tools objectmapper handles marshalling the field input values to java types.  It's a little wonky, but since the two libraries can be used independently I'm not sure how to make it better.

**Comment by miguelaferreira** [comment]
it's indeed a difficult one to solve elegantly. If the interfaces for the `ObjectMapperConfigurer` in both projects would align, then it would be possible to create one configuration bean that would get injected in both sides. It wouldn't be super elegant, but a least would remove the need to configure things twice.

Thanks again for being so active in giving support 👍
