### ISSUE TITLE
Could not find acceptable representation using starter and graphql-java-tools

### ISSUE THREAD

**Issue by snowe2010** [graphql-java/graphql-spring-boot#33]
If there is any way we could get an example project showing how to use the graphql-java-tools with this project I think it would help. I'm currently getting 

```
{
  "timestamp": "2017-09-14T22:09:30.811+0000",
  "status": 406,
  "error": "Not Acceptable",
  "exception": "org.springframework.web.HttpMediaTypeNotAcceptableException",
  "message": "Could not find acceptable representation",
  "path": "/graphiql",
  "correlationId": "26c68e2b-3c2d-49e9-b6e1-ae57d6e8b24e"
}
```

with this code

```

class Query(private val repository: LoanFileViewRepository) : GraphQLQueryResolver {
    fun loanFiles(): List<LoanFile> {
        return repository.findAll().map {
            LoanFile(it.loanId.toString()) //, LoanOfficer(it.loanOfficerId.toString()), LoanProcessor(it.processorId.toString()))
        }
    }
}

@Bean
fun schema(): GraphQLSchema {
    return GraphQLSchema.newSchema().query(GraphQLObjectType.newObject().name("Query").build()).build()
}

class LoanFileResolver : GraphQLResolver<LoanFile>
//class LoanOfficerResolver : GraphQLResolver<LoanOfficer> {
//    fun loanOfficer(id: )
//}

data class LoanFile(
        var id: String
//        var loanOfficer: LoanOfficer,
//        var loanProcessor: LoanProcessor
)

data class LoanOfficer(
    val id: String,
    val name: Name,
    val contactInfo: ContactInfo)

data class LoanProcessor(
    val id: String,
    val name: Name,
    val contactInfo: ContactInfo)

data class Name(
    val first: String,
    val middle: String,
    val last: String,
    val suffix: String
)

data class ContactInfo(
    val phoneNumbers: List<PhoneNumber>,
    val emailAddresses: List<String>
)

data class PhoneNumber(
    val number: String,
    val type: String,
    val extension: String
)

```

```
schema {
    query: QueryType
}

type QueryType {
    loanFile(id: String!) : LoanFile
    loanFiles : [LoanFile]
}

type LoanFile {
    id: String!
#    loanOfficer: LoanOfficer
#    loanProcessor: LoanProcessor
}

type LoanOfficer {
    id: String!
    name: Name!
    contactInfo: ContactInfo
}

type LoanProcessor {
    id: String!
    name: Name!
    contactInfo: ContactInfo
}

type Name {
    first: String
    middle: String
    last: String
    suffix: String
}

type ContactInfo {
    phoneNumbers: [PhoneNumber]
    emailAddresses: [String]
}

type PhoneNumber {
    number: String!
    type: String!
    extension: String
}
```

**Comment by apottere** [comment]
The example on graphql-java-tools might be a little out of date, but it uses the spring-boot-starter: https://github.com/graphql-java/graphql-java-tools/tree/master/example

When your browser hits /graphiql, what Accept header is it using?  That's a really strange error.

**Comment by snowe2010** [comment]
@apottere I'm using the GraphiQL tool installed using brew. so whatever it is using. I tried using postman, but I don't know what header to set it to?

**Comment by apottere** [comment]
Wait, are you trying to hit `localhost:<port>//graphiql` in your graphiql client?  Are you sure you didn't typo `graphiql` meaning `graphql`?

**Comment by snowe2010** [comment]
Yes I'm trying to hit the graphiql endpoint. Is that not what I'm supposed to be doing for introspection? `http://localhost:8080/api/graphiql` (we have a zuul gateway sitting in front of the server)

**Comment by apottere** [comment]
No, `/graphiql` serves up an HTML page that has the GraphiQL client.  If you want to use a different client, point it at the `/graphql` endpoint.

**Comment by snowe2010** [comment]
Gotcha, even doing that though, it does not load my schema. Isn't the schema supposed to be auto detected if you don't have a `GraphQLSchema` bean on the classpath? If I don't have the bean then no schema is loaded and I get the error:

```
{
  "timestamp": "2017-09-15T14:48:05.396+0000",
  "status": 404,
  "error": "Not Found",
  "message": "No message available",
  "path": "/graphql"
}
```

I add the bean and I get:

```
{
  "data": null,
  "errors": [
    {
      "validationErrorType": "FieldUndefined",
      "message": "Validation error of type FieldUndefined: Field loanFiles is undefined",
      "locations": [
        {
          "line": 29,
          "column": 3
        }
      ],
      "errorType": "ValidationError"
    }
  ]
}
```

even though I have a root query resolver:

```
class Query(private val repository: LoanFileViewRepository) : GraphQLQueryResolver {
    fun loanFiles(): List<LoanFile> {
        return repository.findAll().map {
            LoanFile(it.loanId.toString()) //, LoanOfficer(it.loanOfficerId.toString()), LoanProcessor(it.processorId.toString()))
        }
    }
}
```

**Comment by apottere** [comment]
Did you mark your root resolver as a `@Component`?

**Comment by snowe2010** [comment]
No, I thought it was like JPA and the fact that I was extending that interface would resolve it as a bean. Fantastic, that got me one step further. 

```
{
  "data": null,
  "errors": [
    {
      "validationErrorType": "SubSelectionRequired",
      "message": "Validation error of type SubSelectionRequired: Sub selection required for type null",
      "locations": [
        {
          "line": 29,
          "column": 3
        }
      ],
      "errorType": "ValidationError"
    }
  ]
}
```

**Comment by snowe2010** [comment]
Oh it's because I needed to ask for `ids`, usually graphiql will autocorrect that for me. Is that not supported in the spring boot version?

**Comment by apottere** [comment]
The GraphiQL in the spring-boot starter may be slightly out of date, but it should still have validation .  I can double check the released version.

**Comment by apottere** [comment]
Yeah, looks like it's on 0.10.1 but latest is 0.11.3.  I'll update it.

**Comment by snowe2010** [comment]
fantastic! At least this thread accomplished something besides showing my ignorance 😂  

I'll try and make a comparable `graphql-java-tools` example and contribute it, with my understanding. I'll do it in kotlin as well since that's easily convertable to the java representation, but not as easy the other way around.

**Comment by apottere** [comment]
`3.9.1` is syncing to central right now.  Examples are certainly welcome, Thanks!
