### ISSUE TITLE
Property to change GraphiQL's /graphql endpoint

### ISSUE THREAD

**Issue by snowe2010** [graphql-java/graphql-spring-boot#35]
Our app exists behind a zuul router, so even with the default mapping of `/graphql` and `/graphiql`, `/graphiql` is not able to find `/graphql`. Is there anyway to add a property to the `graphiql` config to change the location it looks for `graphql`?

**Comment by blk-addr** [comment]
I had the same issue and found a workaround.  A graphiql.html file in our main project /resources folder seems to have taken care of the issue after removing the leading /, making it `return fetch('graphql', {`.  This successfully pulls the schema when hitting a direct instance (ie local development) or if it is behind zuul.  
Making this configurable would be a plus to make keeping in sync with project updates easier.

**Comment by apottere** [comment]
This is added in the latest version (`graphiql.endpoint`), but you can provide your own graphiql.html and that should work too
