### ISSUE TITLE
Add support for Persisted queries

### ISSUE THREAD

**Issue by raderio** [graphql-java/graphql-spring-boot#37]
Please, add support for Persisted queries.
https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5

Like https://github.com/apollographql/persistgraphql

**Comment by apottere** [comment]
Is this the same as preparsed queries?  If so, this is the issue on the servlet: https://github.com/graphql-java/graphql-java-servlet/issues/39

**Comment by raderio** [comment]
Yeap, is the same.

**Comment by raderio** [comment]
http://graphql-java.readthedocs.io/en/v4/execution.html#query-caching

**Comment by yuhanz** [comment]
Not exactly the same. The persisted query also reduces the size of the payload in the request. The local query caching doesn't have that effect.

**Comment by senzzzi** [comment]
I agree @yuhanz, they are definitely not the same. One thing is caching the validation of the query other is allowing the query to be done with an hash. Not sure if it's implemented or not..
