### ISSUE TITLE
is graphql spring boot compatible with spring security?

### ISSUE THREAD

**Issue by hkashlan** [graphql-java/graphql-spring-boot#38]
Dear all as the title said 
is graphql spring boot compatible with spring security?

and if there is a sample for this

**Comment by apottere** [comment]
Does the discussion on #29 help?

**Comment by hkashlan** [comment]
Thank you for pointing to that issue,
I will try it today with Oauth2 and let you know

**Comment by apottere** [comment]
@hkashlan did that work for you?

**Comment by hkashlan** [comment]
Sorry but I didn't work on it yet, I went back to restful API :(
