### ISSUE TITLE
adding tracing instrumentation

### ISSUE THREAD

**Issue by flarepass** [graphql-java/graphql-spring-boot#52]
Hi, correct me if I'm wrong.
With the graphql-spring-boot-starter, it will handle the bean creation for these object :  GraphQL ,GraphQLSchema, SchemaParser, etc.
and I'm interested with the tracing instrumentation (http://graphql-java.readthedocs.io/en/v6/instrumentation.html) which add TracingInstrumentation to the GraphQL object
I tried to add the tracing instrumentation to my GraphQL object but there's no change to my response 
here is how I try to add the TracingInstrumentation object to my GraphQL object
`
@SpringBootApplication
public class DemographqlApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemographqlApplication.class, args);
    }

    @Bean
    public GraphQL graphQL(GraphQLSchema graphQLSchema) {
        return GraphQL.newGraphQL(graphQLSchema)
                .instrumentation(new TracingInstrumentation())
                .build();
    }

}`

Am I missing something here ?

Thank you

**Comment by apottere** [comment]
The `GraphQL` object is request-scoped, so it's created on every request.  You'll need to implement a https://github.com/graphql-java/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/InstrumentationProvider.java bean that returns the tracing instrumentation.

**Comment by flarepass** [comment]
Hi @apottere,
Thank you for your response, but I have create an implementation of the InstrumentProvider : 
`public class GraphQLInstrumentationProvider implements InstrumentationProvider {
    @Override
    public Instrumentation getInstrumentation() {
        return new TracingInstrumentation();
    }
}` 

and I also provide the bean,
`
    @Bean
    InstrumentationProvider instrumentationProvider() {
        return new GraphQLInstrumentationProvider();
    }`

I'll try to include some detail  of my sample code : 

my schema only contain

`
type Query {
    allLinks: [Link]
}
type Link {
    id: ID!
    url: String!
    description: String
}`

my request : 
`{
	allLinks{
		id
	}
}`
my response : 
`
{
	"data": {
		"allLinks": [
			{
				"id": "1"
			}
		]
	}
}
`

Is there anything else that i missed ?

**Comment by apottere** [comment]
No, that should work.  Is it injecting the InstrumentationProvider into your servlet?

**Comment by flarepass** [comment]
Hi @apottere ,

I think it suppose to provide the InstrumentationProvider bean to the servlet, but as i see in the documentation, http://graphql-java.readthedocs.io/en/v6/instrumentation.html

The instrumentation should be set into the GraphQL  object, that's why at first i tried to create the bean for GraphQL object, but since the GraphQL object is request-scoped, i'm not sure how to add it.

**Comment by apottere** [comment]
The `GraphQL` object is created by the servlet when it gets a request.

**Comment by flarepass** [comment]
Hi @apottere,

I'm still unable to provide the TracingInstrumentation to the GraphQL object.
I have created my implementation and provide the Bean. 

could you give me  example of how to injecting the Instrumentatio Provider?
or Is it possible to keep this issue open so I can get insight from some people that has tried this before?

Thank you

**Comment by apottere** [comment]
Sorry, I was mistaken - you can just add your instrumentation as a bean and it should be picked up:
```
@Bean
Instrumentation instrumentation() {
    return new TracingInstrumentation();
}
```

**Comment by flarepass** [comment]
hi @apottere ,

Did that work for you ?
Since i have tried it, i also have tried provided the TracingInstrumentation as bean before, but there is no change at all.

**Comment by apottere** [comment]
Yes, I tried it in an example project and hit a breakpoint in the TracingInstrumentation

**Comment by flarepass** [comment]
Fixed,
It's because of older version of version of graphql-java-servlet as pointed by [eric taix at Stackoverflow ](https://stackoverflow.com/questions/48273780/adding-apollo-tracing-to-graphql-spring/48547878#48547878) 😅 
Thank you

**Comment by kwang1** [comment]
> Sorry, I was mistaken - you can just add your instrumentation as a bean and it should be picked up:
> 
> ```
> @Bean
> Instrumentation instrumentation() {
>     return new TracingInstrumentation();
> }
> ```

Hi @apottere , are there any detailed documents about which beans can be injected to Spring?

Thanks.
