### ISSUE TITLE
Parse post requests to check authentication

### ISSUE THREAD

**Issue by fmarelli** [graphql-java/graphql-spring-boot#53]
Hi, 

for every request I need to check HttpRequest authorization header to see if it contains a valid token if not I want to set the response status to 401 so that the client can handle it. What it is the best practice for this? I can parse requests using

`@Bean
	public List<GraphQLServletListener> listeners(){`

or 

`@Bean
	public GraphQLContextBuilder contextBuilder() throws Exception {
		return new GraphQLContextBuilder() {

			@Override
			public GraphQLContext build(Optional<HttpServletRequest> req, Optional<HttpServletResponse> resp){

				System.out.println("IN CONTEXT BUILDER");
				String authHeader = req.get().getHeader("Authorization");
				System.out.println("IN REQUEST LISTENER - authHeader: "+authHeader);`

but I don't know how to stop the current request and "force" the response to 401.

It seems like the only solution is to create my own servlet overriding the doPost method, but there must be a better "spring boot" way I presume.

Thanks for any help.

**Comment by icoderman** [comment]
Hi @fmarelli, take a look on https://stackoverflow.com/questions/45959234/authentication-in-spring-boot-using-graphql it should help.

**Comment by fmarelli** [comment]
thanks @icoderman for your reply. Useful information.

**Comment by oliemansm** [comment]
@fmarelli I’m assuming that link provided all the info you needed, therefore closing this issue. Just reopen it if you have any follow up questions.
