### ISSUE TITLE
File upload [Question]

### ISSUE THREAD

**Issue by Nexyll** [graphql-java/graphql-spring-boot#56]
Anyone have an idea about how I can upload a file thru a GraphQL mutation ?

**Comment by ieugen** [comment]
try https://stackoverflow.com/questions/48050509/graphql-spring-boot-upload-binary

**Comment by oliemansm** [comment]
@Nexyll Did you find a solution for the upload? Can you close this issue in that case?

**Comment by Nexyll** [comment]
Yes, I've prefered to create a REST endpoint to handle file upload.
