### ISSUE TITLE
Spring subscription example

### ISSUE THREAD

**Issue by rwilliams-r7** [graphql-java/graphql-spring-boot#60]
I have found the following example https://github.com/graphql-java/graphql-java-subscription-example which use graphql-java for subscriptions over a websocket.

I have been trying to do the same idea within the spring version but have not been able to understand how it fits together. Do we have a spring version of the example above, or something similar?

I have been struggling to understand how the Publisher from GraphQLSubscriptionResolver fits together with websockets.

**Comment by bulka777** [comment]
Isn't [GraphQLSubscriptionResolver](https://github.com/graphql-java/graphql-java-tools/blob/master/src/main/kotlin/com/coxautodev/graphql/tools/GraphQLSubscriptionResolver.java) a concept from graphql-java-tools? There is an example request there as well: https://github.com/graphql-java/graphql-java-tools/issues/88. 

It would be nice to see a reference implementation for it using spring specific websocket support though. Working through that now myself.

**Comment by rwilliams-r7** [comment]
@bulka777, yes trying to work through it myself. I am finding it hard to connect the Publish return value from a class that implements GraphQLSubscriptionResolver, to a given websocket, hope you have more luck.

**Comment by rwilliams-r7** [comment]
@bulka777 did you have any luck?

**Comment by bulka777** [comment]
Didn't really find time to play with it yet. Will post back if I do.

**Comment by Syl1234** [comment]
Any news on how tu use subscription !
I'm not that sure that GraphiQL supports subscription also ?
Is there any documentation related to that subject.

**Comment by reithma** [comment]
Greetings and sorry for reviving this topic.  

Are there any news on this issue or progress on a successful implementation of a subscription in spring?  
I'd be very thankful if someone pointed me to a direction where i could find an example (would gladly try to do a pr if i'm successful and happy with my implementation aswell!)

**Comment by oliemansm** [comment]
PR #95 contains support for subscriptions and a reference implementation in `example-graphql-subscription`. Will merge it once reviews and tests are done.
