### ISSUE TITLE
"/graphql"  is not available when upgrade to springboot 2.0

### ISSUE THREAD

**Issue by herochinese** [graphql-java/graphql-spring-boot#61]
It's works fine under springboot 1.5.x, but it's not available on springboot 2.0.

**Comment by herochinese** [comment]
Can be registered by following way:

    `    @Bean
    public ServletRegistrationBean servletRegistrationBean() {
    
        GraphQLSchema schema  = SchemaParser.newParser().resolvers(new Query(),new Mutation()).file("schema.graphqls").build().makeExecutableSchema();
        ExecutionStrategy executionStrategy = new AsyncExecutionStrategy();
        GraphQLServlet servlet = new SimpleGraphQLServlet(schema, executionStrategy);
        ServletRegistrationBean bean = new ServletRegistrationBean(servlet, "/graphql");
        return bean;
    }`

**Comment by ramsrib** [comment]
Can you guys update the README?


For me, this worked.
```
	@Bean
	GraphQLSchema schema() {
		return GraphQLSchema.newSchema()
				.query(GraphQLObjectType.newObject()
						.name("query")
						.field(field -> field
								.name("test")
								.type(Scalars.GraphQLString)
								.dataFetcher(environment -> "response")
						)
						.build())
				.build();
	}

	@Bean
	public ServletRegistrationBean servletRegistrationBean() {
		ExecutionStrategy executionStrategy = new AsyncExecutionStrategy();
		GraphQLServlet servlet = new SimpleGraphQLServlet(schema(), executionStrategy);
		ServletRegistrationBean bean = new ServletRegistrationBean(servlet, "/graphql");
		return bean;
	}
```

**Comment by herochinese** [comment]
There's changes should be made around default servlet - SimpleGraphQLServlet accordingly.  It should be able to auto scan *. graphqls within classpath.

**Comment by ramsrib** [comment]
Make sense, but the README can be updated with that information. For example, we can add a NOTE saying  `this version 3.10.0 doesn't work with Spring boot 2` or even better, we can add a wiki dedicated for spring boot 2.

**Comment by Mawster** [comment]
I just copied your code and tried to get it runnin with Spring boot 2.0.0 -
The problem is the following line in GraphQLWebAutoConfiguration 
41: @ConditionalOnBean({GraphQLSchema.class, GraphQLSchemaProvider.class})

If you just remove GraphQLSchemaProvider.class everything works fine. Don't know the exact problem yet but I will check that out.

**Comment by shingi** [comment]
Has anyone managed to get this to work at all?

**Comment by apottere** [comment]
The latest version should be fully compatible with spring-boot 2.0

**Comment by khteh** [comment]
How does this work with the new `SimpleGraphQLHttpServlet` which replaces `SimpleGraphQLServlet`?
