### ISSUE TITLE
Allow developers to set the GraphiQL default query and variables

### ISSUE THREAD

**Issue by aSemy** [graphql-java/graphql-spring-boot#64]
I would like set the default query and variables used by GraphiQL so I can easily share useful queries for my schema, and keep track of changes in source control.

As the default query that I'd like to set is very large, I'd like to set this in a separate file, though if I could set it just in application.properties similarly to the pageTitle that would be great.

**Comment by apottere** [comment]
Just to clarify, you want to set the default query in graphiql, right?

**Comment by marceloverdijk** [comment]
Yes @apottere it would be nice to change the `query` and `defaultQuery` parameters of GraphiQL.
