### ISSUE TITLE
Spring Boot Object mapper

### ISSUE THREAD

**Issue by alexcibotari** [graphql-java/graphql-spring-boot#65]
Hello,

I there any possibility to share Jackson Object Mapper between Spring Boot and GraphQL?

Instead of duplicating code like this 

GraphQL
```
@Component
public class GraphQlObjectMapperConfigurer implements ObjectMapperConfigurer {
  @Override
  public void configure(ObjectMapper mapper, ObjectMapperConfigurerContext context) {
    mapper.registerModule(new JavaTimeModule())
        .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
  }
}
```
Spring Boot
```
@Configuration
public class JacksonConfiguration {

  @Bean
  Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder() {
    JavaTimeModule module = new JavaTimeModule();
    return new Jackson2ObjectMapperBuilder()
        .featuresToDisable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
        .serializationInclusion(JsonInclude.Include.NON_NULL)
        .findModulesViaServiceLoader(true)
        .modulesToInstall(module);
  }

}
```

**Comment by apottere** [comment]
This is tough because there are cases where you'll want your graphql object mapper to behave differently than your spring object mapper.  Passing the spring object mapper to graphql-java-servlet automatically would make it impossible to differentiate.

**Comment by mxab** [comment]
I think by default you would expect spring's default object mapper but I also understand that you may want to configure it differently.
Could you add some property like
`...graphql.use-default-objectmapper = false` and then provide a objectmapper with a certain qualifier?

**Comment by mxab** [comment]
@oliemansm I have some suggestion to solve this issue.

First we would need to move the instantiations of  the per field objectmapper in the to a provider/factory
https://github.com/graphql-java/graphql-java-tools/compare/master...mxab:wip/unify-objectmapper
I added also a backward compatible Provider that behaves like the original instantiations using the configurerer.

Similar but only for the one objectmapper that is constructed by the servlet
https://github.com/graphql-java/graphql-java-servlet/compare/master...mxab:wip/unify-objectmapper

Finally can provide these providers that just passthrough the available objectmapper provided by spring boot for both tools and servlet
https://github.com/graphql-java/graphql-spring-boot/compare/master...mxab:wip/unify-objectmapper

**Comment by oliemansm** [comment]
@mxab Nice! I've created PRs for them so we can get them merged and released.

**Comment by oliemansm** [comment]
@mxab Can you give me write permissions on your branch in spring-boot? I merged in master to fix conflicts. That has to be pushed before it can be merged.

**Comment by mxab** [comment]
Cool!
