### ISSUE TITLE
Adding tracing to GraphQL Spring Boot output

### ISSUE THREAD

**Issue by rwilliams-r7** [graphql-java/graphql-spring-boot#66]
Currently graphql-spring-boot is using `LIB_GRAPHQL_SERVLET_VER = 4.6.0`. This does not support tracing in the response.

The latest version https://github.com/graphql-java/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/GraphQLServlet.java adds the tracing data to the response. 

This need upgraded to 4.7.0 which supports this.

**Comment by apottere** [comment]
Fixed.
