### ISSUE TITLE
Are subscriptions over websockets supported?

### ISSUE THREAD

**Issue by jamesmmchugh** [graphql-java/graphql-spring-boot#70]
I'm trying to use graphql-spring-boot with graphql-java-tools to setup an example delivering subscriptions responses over websocket. There's no documentation covering this example, only for querying over HTTP. Is this possible, can the starter be configured to use websockets?

**Comment by jamesmmchugh** [comment]
@apottere I noticed there is a websocket support related branch, do you know if there is plans to finish this work in the near future? 

Also, is this project being actively maintained in general as it's using older versions of graphql-java etc? Its extremely useful to have the spring-boot-starters but i'm wondering if i'd be better off skipping these (and hence auto configuration) and doing the configuration manually so I can take advantage of newer features.

**Comment by assafberg** [comment]
any news on this?

**Comment by apottere** [comment]
Not yet, it's taking more time to get it working than I thought.

**Comment by assafberg** [comment]
would long polling be easier to implement? that could also be useful
