### ISSUE TITLE
Accidental Override when create custom exceptions

### ISSUE THREAD

**Issue by vagostep** [graphql-java/graphql-spring-boot#71]
When i try to create a custom exception that implements GraphQLError cause an Accidental Override in the getMessage error in Kotlin

It's cause because the interface GraphQLError have a abstract method called getMessage(), and the class Throwable also have the same method. 

So, the custom exceptions need extends of Throwable and implements GraphQLError and this cause a compiler error "Accidental Override"

`override fun getMessage(): String {   -> For GraphQLError interface
}
`
`    override val message: String?   -> For Throwable class
        get() = super.message`

**Comment by liqweed** [comment]
This is really an issue with [graphql-java/graphql-java](url). `GraphQLError` type isn't specific to graphql-spring-boot.
