### ISSUE TITLE
Adding ExecutionInput

### ISSUE THREAD

**Issue by AllanWang** [graphql-java/graphql-spring-boot#72]
Is there a way specific to spring boot for adding `ExecutionInput`?

I'm trying to connect graphql with my sql db, and I'm using the [db example](https://github.com/graphql-java/graphql-java-db-example/) for reference. Over there, a `GraphQL` instance is created with each request, whereas in the examples here, a schema is created with a bean. Where would we add additionall hooks to `GraphQL`, or is there any other way of doing this?

**Comment by apottere** [comment]
You can implement `GraphQLContextBuilder` to provide custom data to your context, and you can retrieve the context from the `DataFetchingEnvironment` in your data fetcher.
