### ISSUE TITLE
Cannot make requests from other origin

### ISSUE THREAD

**Issue by BenoitAverty** [graphql-java/graphql-spring-boot#8]
Hello,

I have a graphql api set up with this project, and I'm trying to make a request from a GUI hosted elsewhere.

However, the OPTIONS request always return the following : 
```
HTTP/1.1 200
Allow: GET, HEAD, POST, OPTIONS
Content-Length: 0
Date: Wed, 17 May 2017 19:01:38 GMT
```

And then the browser doesn't perform the request.

I have tried true/false for the property graphql.servlet.corsEnabled, but this didn't change anything.

Do you know How I could configure my app to allow cross-origin requests ?

**Comment by BenoitAverty** [comment]
I've managed to make it work by adding a cors filter myself : 

```
@Bean
    public FilterRegistrationBean corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("*");
        config.addAllowedHeader("*");
        config.addAllowedMethod("*");
        source.registerCorsConfiguration("/**", config);
        FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
        bean.setOrder(0);
        return bean;
    }
```

I haven't been able to understand exactly why it doesn't work with the WebMvcConfigurerAdapter that's setup in the autoconfiguration though. Maybe I'm missing a dependency, or maybe it's a bug, but you can probably solve the problem by adding the filter I've provided instead.

**Comment by apottere** [comment]
Yeah, that's odd.  Does it work if you use `/graphql/* as the cors mapping?

From the docs, it looks like what's in the auto-configuration should *just work*: http://docs.spring.io/spring/docs/current/spring-framework-reference/html/cors.html#_javaconfig

**Comment by apottere** [comment]
The auto-configuration defaults to `/graphql/*` as the servlet mapping, but it's possible for the cors mapping it needs to be `/graphql/**`.

**Comment by BenoitAverty** [comment]
I've replaced `/**` by `/graphql/*` in my bean above and it stopped working, so it looks like you are right. I've also tried `/graphql`, which also works.

**Comment by apottere** [comment]
Can you try `/graphql/**`?  That will probably work for the servlet as well, so that would be nice.

**Comment by BenoitAverty** [comment]
Yes, it does work with `/graphql/**`. The specification mentions ant matchers so indeed,` /graphql/*` is the only one that wouldn't match the url `/graphql`

**Comment by apottere** [comment]
Cool, I'll make that the default for the servlet as well then.

**Comment by apottere** [comment]
So I did a bunch more digging, and it looks like the servlet needs `/grapql/*`, and the cors mapping needs `/grapqhl/**`.  I added a method on the properties to coerce whatever was set into the correct shape.

I also had to register a `CorsFilter` instead of using the webmvc adapter because of the way the path matcher works by default.  Turns out you have to flip a flag to get it to match the whole "servlet path"

**Comment by BenoitAverty** [comment]
Thanks :)

**Comment by casramsey** [comment]
I have this exact same issue and implemented the corsFilter as shown about which solves the problem.  However, two colleagues are able to take the exact same project, remove the corsFilter, fire it up locally and, using the same "different origin" client, not have a cors issue.  Any idea why they don't need the corsFilter and I do, given everything is the same on each PC?  

I'm not entirely sure from the above why we'd need the corsFilter in the first place - is it because there is a bug with the built in WebMvcConfigurerAdapter configured in the properties?

Thanks!

**Comment by sdeleuze** [comment]
`WebMvcConfigurerAdapter` is designed to be taken in account by Spring MVC mappings, if graphql is servlet based, it needs to use the filter approach.

That said, I would be interested to know why there is a need for such `CorsRegistryWorkaround` class? `CorsRegistry` CORS configuration is `protected` on purpose, and if there is a use case that is not possible for you I would be interested to be aware of it.

I know nothing about graphql, but isn't it possible to write `configurationSource.setCorsConfigurations(Collections.singletonMap(graphQLServletProperties.getCorsMapping(), new CorsConfiguration().applyPermitDefaultValues()));`?

**Comment by abhinav-jain09** [comment]
I have the same problem but still not able to solve it . does anyone solved it by graphql properties?

**Comment by abhinav-jain09** [comment]
@BenoitAverty I implimented the filter but it does not work for me .

**Comment by mattc41190** [comment]
I am running into something that seems similar to this.

OpenJDK 11
Kickstart v5

**Comment by srnm** [comment]
I got this working by adding the following in my application.yml:

```
# disable GraphQLWebAutoConfiguration's CORS support and configure CORS the Spring way
graphql.servlet.corsEnabled: false
```

and then using the standard Spring mechanism to configure CORS.
nb: if you use Spring Security - you'll need to enable CORS support for it too.

**Comment by fabiocarvalho777** [comment]
I believe this issue has to be reopened. The expectation is CORS to be enabled by default, but it is not. Maybe some change reintroduced this bug. Was there a regression test added when this was fixed originally?

**Comment by fabiocarvalho777** [comment]
I just opened this new issue here, in case my previous comment here isn't noticed.

https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/261
