### ISSUE TITLE
graphiQL include context into endpoint

### ISSUE THREAD

**Issue by michalgebauer** [graphql-java/graphql-spring-boot#85]
I have servlet context:
server.servlet.context-path=/app

but by default graphiQL expects endpoint to be in the root /graphql
I had to manually prepend my context path to get it work:
graphiql.endpoint=/app/graphql

Would be nice if this is done automatically to avoid hard-coded urls

thanks.

**Comment by pclnzwang** [comment]
server.servlet.path=/app
should work. However, a fix version of this issue would be ideal.

**Comment by oliemansm** [comment]
This will be part of the next release.

**Comment by pclnzwang** [comment]
@oliemansm Thank you for letting us know that!
