### ISSUE TITLE
GraphQLJavaToolsAutoConfiguration should close any open input streams

### ISSUE THREAD

**Issue by ojecborec** [graphql-java/graphql-spring-boot#87]
In the method `GraphQLJavaToolsAutoConfiguration.schemaParser` the line

`IOUtils.copy(resource.getInputStream(), writer);`

should be changed to

```
try (val in = resource.getInputStream()) {
    IOUtils.copy(in, writer);
}
```

**Comment by oliemansm** [comment]
I've added this to my refactoring of this part.
