### ISSUE TITLE
Make `query` and `defaultQuery` configurable

### ISSUE THREAD

**Issue by marceloverdijk** [graphql-java/graphql-spring-boot#89]
It would be nice to make e.g. `query` and `defaultQuery` configurable using properties.
Maybe check https://github.com/graphql/graphiql#usage for al graphiql options available.

**Comment by oliemansm** [comment]
Looks like a duplicate of #64. Maybe close this one and upvote the other one?

**Comment by marceloverdijk** [comment]
Closing as duplicate of #64.
