### ISSUE TITLE
Make graphqls resources path configurable.

### ISSUE THREAD

**Issue by marceloverdijk** [graphql-java/graphql-spring-boot#90]
Currently the hardcoded path `classpath*:**/*.graphqls` is used: https://github.com/graphql-java/graphql-spring-boot/blob/master/graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.java#L57

It would be nice to make this configurable to e.g. only look into `classpath*:graphql/*.graphqls`.
The current `**/` will search in every subfolder of every jar file on the classpath...

**Comment by oliemansm** [comment]
I was working on this part a while back locally to make it easier to provide schemas for unit tests. I saw your request, so decided to make it configurable and create a PR for it. See #91 

It adds the property `graphql.tools.schemaLocationPattern` for this purpose.

**Comment by marceloverdijk** [comment]
@oliemansm 👍
