### ISSUE TITLE
ObjectMapperConfigurer not working (anymore)

### ISSUE THREAD

**Issue by mxab** [graphql-java/graphql-spring-boot#97]
Hi,
I [registered](https://github.com/mxab/graphql-spring-boot/blob/javatime/example-graphql-tools/src/main/java/com/embedler/moon/graphql/boot/GraphQLToolsSampleApplication.java#L18) a `graphql.servlet.ObjectMapperConfigurer` bean that applies the `JavaTimeModule` but it seems that it does not work and I'm getting the error:

```
Cannot construct instance of `java.time.LocalDateTime` (no Creators...
```

See this [showcase test](https://github.com/mxab/graphql-spring-boot/blob/javatime/example-graphql-tools/src/test/java/com/embedler/moon/graphql/boot/GraphQLToolsSampleApplicationTest.java#L35)

It show cases a [mutation](https://github.com/mxab/graphql-spring-boot/blob/javatime/example-graphql-tools/src/main/resources/graphql-tools.graphqls#L18) that [creates a post](https://github.com/mxab/graphql-spring-boot/blob/javatime/example-graphql-tools/src/test/resources/graphql/create-post.graphql). The schema contains a `PostInput` with a date string field. The Java PostInput type is a LocalDateTime.

The full diff: https://github.com/graphql-java/graphql-spring-boot/compare/master...mxab:javatime

**Comment by oliemansm** [comment]
I'm not seeing the related `PostInput` class in your branch. I think you haven't pushed everything yet? And the `.graphqls` file shows the following definition currently using a `String` instead of your own custom scalar for a `Date` or `DateTime`. I'm assuming in your local version that's different seeing the errors you're getting?
```
input PostInput {
    date: String
}
```
You could try the following config for your `ObjectMapperConfigurer`:
```java
@Bean
public ObjectMapperConfigurer objectMapperConfigurer(){
    return mapper -> mapper.registerModule(new JavaTimeModule())
            .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
}
```
Because of the mentioned missing items I couldn't really test it properly with the test case you provided. 

Nice improvements to that test util! Was thinking about extracting it together with some other features into a `graphql-spring-boot-starter-test` to ease testing of GraphQL.

**Comment by mxab** [comment]
Hi,
the `PostInput` class is a static class inside the `Mutation` class.
As far as I understand the project you don't necessarily need a custom scalar as the mapping happens from a `Map`with the input value to the target class

**Comment by mxab** [comment]
I like the idea with regarding the `graphql-spring-boot-starter-test`

**Comment by oliemansm** [comment]
Found the `PostInput` class, thanks. Will take a look.

**Comment by oliemansm** [comment]
Just saw that in of my own projects as well how to configure it. Glad you found it. There's already an open issue if it's possible to just use one `ObjectMapperConfigurer`, but there were some concerns about that idea, see #65.

**Comment by mxab** [comment]
What confuses me know is what the purpose of the `graphql.servlet.ObjectMapperConfigurer` is and what object mapper it configures as it seems that its mapper is not used at all

**Comment by oliemansm** [comment]
Quickly looking at the current branch it indeed doesn't seem to be used. If you check the `subscription-support` branch for `graphql-servlet` you'll see that it is used there (through the `GraphQLObjectMapper`). See #95 and [Subscription support](https://github.com/graphql-java/graphql-java-servlet/pull/88).

**Comment by mxab** [comment]
Hi,
I haven't looked at the whole java-graphql tool ecosystem, but I don't understand why you would need to different interfaces of ObjectMapperConfigurer for one setup.  (`javax.servlet`/`com.coxautodev.graphql.tools`). And from what I understand they both have nothing todo with spring boots default objectmapper

**Comment by oliemansm** [comment]
Don't know that either, perhaps it can be cleaned up. @apottere Any light you could shed on this?

**Comment by mxab** [comment]
Hi, I saw that on the `graphql.tools`  there is a ObjectMapper is created for each fielddefintion it encounters, which is a valid option. I toyed a bit arround to allow unifying the object mappers . see further comments here: https://github.com/graphql-java/graphql-spring-boot/issues/65#issuecomment-413170177

**Comment by dhudec** [comment]
The resolution here is not completely clear. I would like to see the documentation improved, at the very least. I had to implement a combination of an ObjectMapperConfigurer with a custom schemaParserOptions bean, as [maxb](https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/97#issuecomment-406863752) pointed out.

**Comment by Nxtra** [comment]
> The resolution here is not completely clear. I would like to see the documentation improved, at the very least. I had to implement a combination of an ObjectMapperConfigurer with a custom schemaParserOptions bean, as [maxb](https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/97#issuecomment-406863752) pointed out.

Sounds great. Can you share how you did that?
